Fixed random function.
Signed-off-by: vimes666 <vimes@xs4all.nl>

diff --git a/lmm-slidez b/lmm-slidez
--- a/lmm-slidez
+++ b/lmm-slidez
@@ -1,14 +1,22 @@
 #!/bin/bash
 # Slideshow generator for Linux Mint Mate by vimes666
  
-version="${0##*/} - version 2.5"
+version="${0##*/} - version 2.9"
 input_folder="/usr/share/backgrounds"
 output_file="$HOME/.backgrounds/slideshow.xml"
 duration=300
 maxdepth=2147483647   # default maximum
+doannotate=false
+randomize=false
+overwrite=false
 cnt=0
-usage="Usage: ${0##*/} [-f] [-h] [-r] [-v] [-d duration] [-i input-folder] [-m maxdepth] [-o output-file]"
+usage="Usage: ${0##*/} [-f] [-h] [-r] [-v] [-d duration] [-a annotation-type ] [-i input-folder] [-m maxdepth] [-o output-file]"
 
+# Annotate and copy the images
+function annotate_files {
+   echo "Annotation $annotation not implemented yet."
+}
+ 
 # Write the startdate section
 function write_heading {
    echo "<!-- Slideshow generated by $version, $(date +'%Y-%m-%d %H:%M:%S') -->" > $output_file
@@ -46,15 +54,16 @@ function write_tail {
 }
 
 # check switches
-while getopts d:fhi:m:o:rv opt; do
+while getopts a:d:fhi:m:o:rv opt; do
    case $opt in
+      a)  doannotate=true && annotation=$OPTARG ;;
       d)  duration=$OPTARG ;;
-      f)  overwrite=TRUE ;;
+      f)  overwrite=true ;;
       h)  echo "$usage" && exit 0 ;;
       i)  input_folder=$OPTARG ;;
       m)  maxdepth=$OPTARG ;;
       o)  output_file=$OPTARG ;;
-      r)  randomize=TRUE ;;
+      r)  randomize=true ;;
       v)  echo $version && exit 0 ;;
       *)  echo "$usage" && exit 1 ;;
    esac
@@ -77,26 +86,36 @@ if [ ! -d "$input_folder" ]; then
    exit 1
 fi
 
-pictures=$(find $input_folder -maxdepth $maxdepth -iname "*.jp*g" -o -iname "*.png" -o -iname "*.gif")   # Get the filenames of the pictures
+if "$doannotate"; then
+   case $annotation in
+      file-name)  annotate_files ;;
+      file-path)  annotate_files ;;
+      author)     annotate_files ;;
+      *)          echo 'Invalid annotation type.' && exit 1 ;;
+   esac
+fi
 
-if [ -z "$pictures" ]; then
-   echo "No images found."
+images=$(find $input_folder -maxdepth $maxdepth -iname "*.jp*g" -o -iname "*.png" -o -iname "*.gif")   # Get the filenames of the images
+
+if [ -z "$images" ]; then
+   echo "No images found in $input_folder"
    exit 1
 fi
 
-if [ $randomize ]; then
-   pictures=$(echo "$pictures"|sort -R)
+if "$randomize"; then
+   temp=$(sort -R --random-source=/dev/urandom <<< "$images")
+   images="$temp"
 fi
 
 if [ -w $output_file  ]; then    
-   if [ $overwrite ]; then
+   if "$overwrite"; then
       answer=$overwrite
    else
       echo -e "$output_file already exists, do you want to replace it? - Y/\e[4mN\e[0m"
       read answer
    fi
    case $answer in
-      [yY]|yes|Yes|YES|TRUE) echo "Replacing $output_file" ;;
+      [yY]|yes|Yes|YES|true) echo "Replacing $output_file" ;;
       *) echo "${0##*/} stopped" && exit 1 ;;
    esac
 fi  
@@ -111,7 +130,9 @@ while read -r line; do
    fi
    ((cnt++))
    prevline=$line
-done <<< "$pictures"
+done <<< "$images"
 write_tail
+
+dconf write /org/mate/desktop/background/picture-filename "'$output_file'"  # Activate slideshow
 
 echo "Slideshow '$output_file' created with $cnt images."
